### ISSUE TITLE
I get "no such module" error after importing from GitHub

### ISSUE THREAD

**Issue by TwoDeen** [finestructure/Arena#103] opened 2024-05-10 05:49 UTC
when I try this `arena https://github.com/pointfreeco/swift-parsing.git`
`import Parsing` No such module 'Parsing'

when I try Product -> Build
the package dependencies disappear!

Xcode version: Version 15.3 (15E204a)
Swift: Apple Swift version 5.10
MacOS: macOS Sonoma Version 14.4.1

What am I doing wrong? Thanks

**Comment by TwoDeen** [comment] 2024-05-10 06:04
I noticed that I can import the library without error in the normal project source code 
but the import does NOT work in the created playground!

**Comment by finestructure** [comment] 2024-05-10 14:35
Mmm, I can't reproduce this. However, there's one thing you need to bear in mind when using a package with macros: you need to enable them before the package can be built.

```
❯ arena pointfreeco/swift-parsing
➡️  Package: https://github.com/pointfreeco/swift-parsing @ from(0.13.0)
🔧 Resolving package dependencies…
📔 Libraries found: Parsing
✅ Created project in folder 'Arena-Playground'
```

![CleanShot 2024-05-10 at 16 31 32@2x](https://github.com/finestructure/Arena/assets/65520/d1b478d1-63aa-40d3-a1b1-0024efabaf44)
![CleanShot 2024-05-10 at 16 33 51@2x](https://github.com/finestructure/Arena/assets/65520/603d005e-4b0a-4cea-a28e-1510819984c0)

**Comment by finestructure** [comment] 2024-05-12 12:21
Closing this, please reopen if the problem persists!

**Closed as not planned** 2024-05-12 12:21 UTC
